# Grafana автоматически создает datasource Tempo при старте.
apiVersion: 1

datasources:
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: '-5m' # запас по времени, т.к. лог и span пишутся не идеально синхронно
        spanEndTimeShift: '5m'
        tags:
          - key: 'service.name'
            value: 'service_name'
      nodeGraph:
        enabled: true
