# Grafana загружает правила алертов, без ручной настройки через UI.

apiVersion: 1
groups:
  - orgId: 1
    name: Тест
    folder: Financial Nano Gateway
    interval: 1m
    rules:
      - uid: aflrjuwiha800d
        title: Глубина очереди АХТУНГ
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: prometheus
            model:
              datasource:
                type: prometheus
                uid: prometheus
              editorMode: code
              expr: sum(payment_queue_depth)
              instant: true
              interval: ""
              intervalMs: 5000
              legendFormat: очередь
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            queryType: expression
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1000
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        dashboardUid: adxhhjv
        panelId: 7
        noDataState: NoData
        execErrState: Error
        annotations:
          __dashboardUid__: adxhhjv
          __panelId__: "7"
          description: Много в очереди
          summary: Тест алерта
        labels: {}
        isPaused: false
        #notification_settings:
         # receiver: Telegram # Куда отправлять сообщение. Этот момент надо будет настроить в UI графаны.
